services:
#    dusan_simple.example:
#        class: Dusan\Bundle\SimpleBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
#parameters:
#    dusan_simple.simple_crud.entity.class: Dusan\Bundle\SimpleBundle\Entity\SimpleCrud
